server:
  port: 8003
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://eureka2:8004/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true
